server:
  port: 80
  
spring: 
  redis: 
    database: 1
    host: IP
    port: 6379
    #password: E2071d7b!81B2Ba8
    timeout: 3000
    pool: 
      max-active: 200  
      max-wait: 10000 
      max-idle: 10 
      min-idle: 0  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ip:3306/movie?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  
logging:
  config: classpath:logback.xml
  
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"

movieFan: 
  #url: http://test.api.moviefan.com.cn/api/ 
  url: http://api.moviefan.com.cn/api/ 
  code: 111
  secret: 111dd
  insertSize: 100000
  
job: 
  # 每天凌晨1点执行一次
  updateAllJob: 0 0 1 * * ? 
  # 从1点30分钟开始, 每30分钟执行一次
  # updateShowJob: 0 0/30 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * ? 
  
wx: 
  appid: qwdas
  
seats:
  # 秒
  lockTime: 3
  # 分钟
  dbLockTime: 30
  
